# Generated by Django 3.0.5 on 2020-05-31 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tts_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_text', models.TextField()),
                ('tts_file', models.FileField(upload_to=tts_app.models.user_directory_path)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='ttsmodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice', models.FileField(upload_to=tts_app.models.user_directory_path)),
                ('text', models.TextField()),
                ('duration', models.FloatField(default=0)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='traindatas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
