# Generated by Django 3.0.5 on 2020-06-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts_app', '0002_traindata_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tts',
            name='tts_file',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
