# Generated by Django 3.0.5 on 2020-05-31 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharer_name', models.CharField(max_length=50)),
                ('sharee_name', models.CharField(max_length=50)),
                ('listening_noti', models.BooleanField(default=True)),
                ('download_noti', models.BooleanField(default=True)),
                ('download_auth', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('sharer_name', 'sharee_name')},
            },
        ),
        migrations.CreateModel(
            name='Share_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_type', models.PositiveSmallIntegerField()),
                ('req_text', models.TextField()),
                ('if_approve', models.PositiveSmallIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('share_id', models.ForeignKey(db_column='share_id', on_delete=django.db.models.deletion.CASCADE, related_name='share_infos', to='share_app.Share')),
            ],
        ),
    ]
