# Generated by Django 3.0.5 on 2020-04-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_type', models.PositiveSmallIntegerField()),
                ('req_text', models.TextField()),
                ('if_approve', models.PositiveSmallIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('share_id', models.ForeignKey(db_column='share_id', on_delete=django.db.models.deletion.CASCADE, to='share_app.Share')),
            ],
        ),
    ]
