# Generated by Django 3.0.5 on 2020-04-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='progess',
            new_name='progress',
        ),
    ]
